// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Objective.PriceTracker.Api.Services.Database;

#nullable disable

namespace Objective.PriceTracker.Api.Migrations
{
    [DbContext(typeof(PriceTrackerDbContext))]
    [Migration("20260619144412_MakeApartmentIdUniqueIndex")]
    partial class MakeApartmentIdUniqueIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("price_tracking")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Objective.PriceTracker.Api.Models.Database.DbApartmentPriceTracker", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ApartmentId")
                        .HasColumnType("integer");

                    b.Property<double?>("LastPrice")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentId")
                        .IsUnique();

                    b.ToTable("apartment_price_trackers", "price_tracking");
                });

            modelBuilder.Entity("Objective.PriceTracker.Api.Models.Database.DbSubscriber", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("SubscriberMail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SubscriberMail")
                        .IsUnique();

                    b.ToTable("subscribers", "price_tracking");
                });

            modelBuilder.Entity("Objective.PriceTracker.Api.Models.Database.DbSubscription", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ApartmentTrackerId")
                        .HasColumnType("bigint");

                    b.Property<long>("SubscriberId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentTrackerId");

                    b.HasIndex("SubscriberId", "ApartmentTrackerId")
                        .IsUnique();

                    b.ToTable("subscriptions", "price_tracking");
                });

            modelBuilder.Entity("Objective.PriceTracker.Api.Models.Database.DbSubscription", b =>
                {
                    b.HasOne("Objective.PriceTracker.Api.Models.Database.DbApartmentPriceTracker", "ApartmentTracker")
                        .WithMany("Subscriptions")
                        .HasForeignKey("ApartmentTrackerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Objective.PriceTracker.Api.Models.Database.DbSubscriber", "Subscriber")
                        .WithMany()
                        .HasForeignKey("SubscriberId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ApartmentTracker");

                    b.Navigation("Subscriber");
                });

            modelBuilder.Entity("Objective.PriceTracker.Api.Models.Database.DbApartmentPriceTracker", b =>
                {
                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
